[package]
name = "ethereum-block-analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = "0.18.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
